language: node_js
services:
  - docker
before_script:
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
script:
  - npm run migrate
  - npm run test
after_success:
  - test $TRAVIS_BRANCH = "master" && 
    (npm run ropsten && npm install -g travis-deploy-once && travis-deploy-once "npm run semantic-release")
