language: node_js
services:
  - docker
before_script:
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
script:
  - npm run migrate
  - npm run test
  - npm run ropsten
after_success:
  - npm run semantic-release