language: node_js
services:
  - docker
before_script:
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest
script:
  - npm run migrate
  - npm run test
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"